<script lang="ts">
  import { onMount } from 'svelte';
  import type { TimelineWord } from './api';

  let {
    words,
    wpm = 350,
    compact = false,
    loopPauseMs = 1200,
  }: {
    /** Pre-computed timeline words (generated by flick-core — see demos.ts). */
    words: TimelineWord[];
    wpm?: number;
    compact?: boolean;
    loopPauseMs?: number;
  } = $props();

  const reduced =
    typeof window !== 'undefined' &&
    window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // Under reduced motion show a static, representative word instead of a loop.
  let index = $state(0);
  let playing = $state(false);

  // rAF accumulator, same discipline as the real reader (never setTimeout chains).
  let raf = 0;
  let last = 0;
  let acc = 0;
  let holdUntil = 0; // pause between loops

  function duration(i: number): number {
    return words[i][2] * (60000 / wpm);
  }

  function frame(now: number) {
    if (!playing) return;
    if (holdUntil > 0) {
      if (now >= holdUntil) {
        holdUntil = 0;
        index = 0;
        acc = 0;
      }
      last = now;
      raf = requestAnimationFrame(frame);
      return;
    }
    acc += now - last;
    last = now;
    let dur = duration(index);
    while (acc >= dur) {
      acc -= dur;
      if (index + 1 >= words.length) {
        holdUntil = now + loopPauseMs;
        break;
      }
      index += 1;
      dur = duration(index);
    }
    raf = requestAnimationFrame(frame);
  }

  function play() {
    if (playing || words.length === 0) return;
    playing = true;
    holdUntil = 0;
    acc = 0;
    last = performance.now();
    raf = requestAnimationFrame(frame);
  }

  function pause() {
    playing = false;
    cancelAnimationFrame(raf);
  }

  function toggle() {
    if (playing) pause();
    else play();
  }

  onMount(() => {
    if (reduced) index = Math.min(2, Math.max(0, words.length - 1));
    else play();
    return () => cancelAnimationFrame(raf);
  });

  const fallback: TimelineWord = ['', 0, 1];
  const current = $derived(words[index] ?? fallback);
  const pre = $derived(current[0].slice(0, current[1]));
  const pivot = $derived(current[0].charAt(current[1]));
  const post = $derived(current[0].slice(current[1] + 1));
</script>

<button
  type="button"
  class="demo-stage"
  class:compact
  onclick={toggle}
  aria-label={playing ? 'Pause demo' : 'Play demo'}
>
  {#if !compact}
    <span class="rail top"></span>
    <span class="rail bottom"></span>
  {/if}
  <span class="notch top"></span>
  <span class="notch bottom"></span>
  <span class="word demo-word">
    <span class="pre">{pre}</span><span class="orp">{pivot}</span><span class="post">{post}</span>
  </span>
</button>
