const r = await fetch('http://127.0.0.1:9333/json/version'); const { webSocketDebuggerUrl } = await r.json() as any;
const ws = new WebSocket(webSocketDebuggerUrl);
let id = 0; const pend = new Map();
const send = (method: string, params: any = {}, sid?: string) => { const i = ++id; ws.send(JSON.stringify({ id: i, method, params, ...(sid ? { sessionId: sid } : {}) })); return new Promise<any>((res, rej) => pend.set(i, { res, rej })); };
await new Promise<void>((res) => (ws.onopen = () => res()));
ws.onmessage = (ev) => { const m = JSON.parse(String(ev.data)); if (m.id && pend.has(m.id)) { const p = pend.get(m.id); pend.delete(m.id); m.error ? p.rej(new Error(m.error.message)) : p.res(m.result); } };
const { browserContextId } = await send('Target.createBrowserContext', {});
const { targetId } = await send('Target.createTarget', { url: 'about:blank', browserContextId });
const { sessionId } = await send('Target.attachToTarget', { targetId, flatten: true });
await send('Page.enable', {}, sessionId);
await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }, sessionId);
await send('Page.navigate', { url: 'http://localhost:8484/' }, sessionId);
await Bun.sleep(1000);
await send('Runtime.evaluate', { expression: `fetch('/api/auth/guest',{method:'POST',credentials:'include'}).then(r=>r.status)`, awaitPromise: true }, sessionId);
await send('Page.navigate', { url: 'http://localhost:8484/' }, sessionId);
await Bun.sleep(1400);
await send('Runtime.evaluate', { expression: `document.querySelector('.rcard')?.click()`, awaitPromise: true }, sessionId);
await Bun.sleep(1500);
await send('Runtime.evaluate', { expression: `document.querySelector('.zenbtn')?.click()`, awaitPromise: true }, sessionId);
await Bun.sleep(500);
const { data } = await send('Page.captureScreenshot', { format: 'png' }, sessionId);
await Bun.write('/home/philip/.claude/jobs/aac5949e/tmp/57-zen-fixed.png', Buffer.from(data, 'base64'));
console.log('done');
process.exit(0);
