const DEBUG_PORT = 9230;
const OUT = "/home/philip/.claude/jobs/aac5949e/tmp/v031";
import { writeFileSync, rmSync } from "node:fs";
rmSync(`${OUT}-prof2`, { recursive: true, force: true });
const proc = Bun.spawn(["brave","--headless=new",`--remote-debugging-port=${DEBUG_PORT}`,"--no-first-run","--disable-gpu",`--user-data-dir=${OUT}-prof2`,"about:blank"],{stdout:"ignore",stderr:"ignore"});
async function waitForCdp(){for(let i=0;i<60;i++){try{const r=await fetch(`http://127.0.0.1:${DEBUG_PORT}/json/list`);const t=await r.json() as any[];const p=t.find(x=>x.type==="page");if(p)return p.webSocketDebuggerUrl;}catch{}await Bun.sleep(250);}throw new Error("no cdp");}
const ws=new WebSocket(await waitForCdp());await new Promise(ok=>ws.onopen=ok);
let id=0;const pend=new Map();ws.onmessage=e=>{const m=JSON.parse(String(e.data));if(m.id&&pend.has(m.id)){pend.get(m.id)(m);pend.delete(m.id);}};
const cdp=(m:string,p:object={})=>{const i=++id;ws.send(JSON.stringify({id:i,method:m,params:p}));return new Promise<any>(ok=>pend.set(i,ok));};
const js=async(x:string)=>(await cdp("Runtime.evaluate",{expression:x,awaitPromise:true,returnByValue:true})).result?.result?.value;
await cdp("Page.enable");await cdp("Runtime.enable");
await cdp("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:2,mobile:true});
await cdp("Page.navigate",{url:"http://127.0.0.1:8492/"});await Bun.sleep(1200);
await js(`fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({email:"p@t.dev",password:"testpass123"})}).then(r=>r.status)`);
await cdp("Page.navigate",{url:"http://127.0.0.1:8492/"});await Bun.sleep(1200);
await js(`[...document.querySelectorAll(".linklike")].find(b=>/\\+ /.test(b.textContent))?.click()`);await Bun.sleep(500);
await js(`document.getElementById("add-url")?.scrollIntoView({block:"center"})`);await Bun.sleep(400);
const overflow = await js(`document.documentElement.scrollWidth > document.documentElement.clientWidth`);
console.log("horizontal overflow:", overflow);
const r=await cdp("Page.captureScreenshot",{format:"png"});
writeFileSync(`${OUT}/p5b-urlrow-fixed.png`,Buffer.from(r.result.data,"base64"));
proc.kill();console.log("done");
